# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('idFuncao', models.AutoField(primary_key=True, serialize=False)),
                ('descricaoFuncao', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFuncionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('CPF', models.IntegerField()),
                ('idFuncao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcao', to='empresa.Funcao')),
            ],
        ),
        migrations.CreateModel(
            name='Garagem',
            fields=[
                ('idGaragem', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=255)),
                ('quantVagas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('idOnibus', models.AutoField(primary_key=True, serialize=False)),
                ('marcaOnibus', models.CharField(default='', max_length=140)),
                ('modeloOnibus', models.CharField(default='', max_length=140)),
                ('garagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garagem', to='empresa.Garagem')),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('idRota', models.AutoField(primary_key=True, serialize=False)),
                ('destino', models.CharField(max_length=140)),
                ('partida', models.CharField(max_length=140)),
                ('horario', models.DateField()),
                ('valorPassagem', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('idViagem', models.AutoField(primary_key=True, serialize=False)),
                ('horarioPrevisto', models.DateField()),
                ('quantPassageiros', models.IntegerField()),
                ('idFuncionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='empresa.Funcionario')),
                ('idOnibus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onibus', to='empresa.Onibus')),
                ('idRota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rota', to='empresa.Rota')),
            ],
        ),
    ]
