# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_rota_nomerota'),
    ]

    operations = [
        migrations.AddField(
            model_name='onibus',
            name='placa',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='rota',
            name='destino',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='rota',
            name='nomeRota',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='rota',
            name='partida',
            field=models.CharField(default='', max_length=140),
        ),
    ]
