# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20170725_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='diaDaSemana',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default='', max_length=1),
        ),
    ]
