# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_rota_diadasemana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='horarioPrevisto',
        ),
        migrations.AddField(
            model_name='viagem',
            name='horario',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rota',
            name='diaDaSemana',
            field=models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
    ]
